extracts = {
    'extract_1': "Domestic Subsidiary. ARTICLE 6 NEGATIVE COVENANTS Until the Commitments shall have expired or been terminated and the principal of and interest on each Loan and all fees payable hereunder shall have been paid in full, the Borrower covenants and agrees with the Lenders that: Section 6.01. Indebtedness. The Borrower will not, and will not permit any Subsidiary to, create, incur, assume or permit to exist any Indebtedness, except: (a) Indebtedness created under (i) the Credit Documents and (ii) the Bridge Facility; (b) Indebtedness of the Borrower or any Subsidiary owing to the Borrower or any other Subsidiary; provided that (i) such Indebtedness shall not have been transferred to any Person other than the Borrower or any Subsidiary and (ii) any such Indebtedness owing by any Credit Party to a Subsidiary that is not a Credit Party shall be subordinated to the Obligations on terms customary for intercompany subordinated Indebtedness, as reasonably determined by the Administrative Agent; ",
    'extract_2': "(c) Guarantees by the Borrower or any Subsidiary of any Indebtedness of the Borrower or any other Subsidiary, other than (i) Guarantees of Permitted Subordinated Indebtedness if such Guarantees are not permitted by the deﬁnition of the term “Permitted Subordinated Indebtedness” and (ii) Guarantees of Indebtedness referred to in clause (e) below if such Guarantees are not permitted by such clause; (d) (i) Capital Lease Obligations,  (ii) Indebtedness incurred to ﬁnance the acquisition, construction or improvement of any ﬁxed or capital assets or assumed in connection with the acquisition of any such assets, and (iii) Reﬁnancing Indebtedness in respect of any such other Indebtedness incurred pursuant to clause (i) or (ii); provided that (A) the aggregate amount of Sale/Leaseback Transactions and Reﬁnancing Indebtedness in respect thereof shall not exceed $750,000,000 and (B) the aggregate amount of Indebtedness incurred in reliance on this subsection ",
    'extract_3': "(d) shall not exceed $3,000,000,000 at any time outstanding (exclusive of the amount of the Capital Lease Obligations in respect of the Borrower’s headquarters complex and any Reﬁnancing Indebtedness in respect thereof) and (C) in the case of any Indebtedness referred to in clause (ii) above, such Indebtedness is incurred prior to or within 270 days after such acquisition or the completion of such construction or improvement and the principal amount of such Indebtedness does not exceed the cost of acquiring, constructing or improving such ﬁxed or capital assets; 53 (e) Indebtedness of any Person that becomes a Subsidiary (or of any Person not previously a Subsidiary that is merged or consolidated with or into a Subsidiary in a transaction permitted hereunder) after the date hereof, and Reﬁnancing Indebtedness in respect thereof; ",
    # 'extract_4': "entered into in the ordinary course of business or (B) contained in security agreements securing Indebtedness of a Restricted Subsidiary to the extent such encumbrance or restriction restricts the transfer of the property subject to such security agreements, (vi) any restrictions with respect to a Restricted Subsidiary imposed pursuant to an agreement that has been entered into in connection with the Disposition of all or substantially all of the Capital Stock or assets of such Restricted Subsidiary, (vii) (xi) customary restrictions and conditions contained in any agreement relating to the Disposition of any property permitted by Section 8.5 pending the consummation of such Disposition, (xii) customary provisions in joint venture agreements and other similar agreements applicable to joint ventures,",
    'extract_4': "provided that (i) such Indebtedness exists at the time such Person becomes a Subsidiary (or is so merged or consolidated) and is not created in contemplation of or in connection with such Person becoming a Subsidiary (or such merger or consolidation) and (ii) the aggregate principal amount of Indebtedness permitted by this clause (e) shall not exceed $500,000,000 at any time outstanding; (f) Indebtedness owed in respect of overdrafts and related liabilities arising from treasury, depository and cash management services or in connection with any automated clearing-house transfers of funds; (g) Permitted Subordinated Indebtedness; and (h) other Indebtedness of the Borrower or any Subsidiary; provided that the aggregate principal amount of such Indebtedness,",
    # 'extract_5': "otherwise disclosed in such ﬁnancial statements), subject to, in the case of ﬁnancial statements delivered pursuant to Section 5.01(a) of the Credit Agreement, changes resulting from audit and normal year end adjustments. (e) All notices and certiﬁcates required to be provided by the Borrower pursuant to Sections 5.01(d), 5.01(e) and 5.07 of the Credit Agreement have been provided in accordance with such Sections. (f) Set forth on Annex B hereto are reasonably detailed calculations of the aggregate amount of Capital Lease Obligations and other Indebtedness outstanding under Section 6.01(d) or Section 6.01(h) of the Credit Agreement as of [mm/dd/yy] . [Signature page follows] Must be the last day of the most recent Fiscal Quarter covered by the ﬁnancial statements attached hereto as Exhibit A or, if reasonably available, a recent date prior to the date of delivery of this Compliance Certiﬁcate.",
    # 'extract_6': "1 1 The foregoing certiﬁcations, together with the description and computations set forth on Annexes A and B, respectively, and the ﬁnancial statements attached hereto as Exhibit A, are made and delivered on [mm/ dd/yy] pursuant to Section 5.01(c) of the Credit Agreement. FACEBOOK, INC., by Name: Title: Annex A to Compliance Certiﬁcate Defaults and Events of Default Annex B to Compliance Certiﬁcate Indebtedness Under Section 6.01 of the Credit Agreement All amounts set forth as of [mm/dd/yy] (I) Indebtedness created under the Credit Documents (Section 6.01(a)(i)): $ [ , , ] (II) Capital Lease Obligations (exclusive of (i) the amount of the Capital Lease Obligations in respect of the Borrower’s headquarters complex and (ii) Sale/Leaseback Transactions) (Section 6.01(d)(i)): $ [ , , ] (III) Indebtedness incurred to ﬁnance the acquisition, construction or improvement of any ﬁxed or capital assets or assumed in connection with the acquisition of any such assets (Section 6.01(d)(ii)): $ [ , , ]",
    # # 'extract_8': "that shall not have been vacated, discharged, or stayed or bonded pending appeal within 60 days from the entry thereof; or (iv) the Borrower or any Material Subsidiary shall take any action in furtherance of, or indicating its consent to, approval of, or acquiescence in, any of the acts set forth in clause (i), (ii), or (iii) above; or (v) the Borrower or any Material Subsidiary shall generally not, or shall be unable to, or shall admit in writing its inability to, pay its debts as they become due; or 134 (g) (i) any Person shall engage in any non-exempt “prohibited transaction” (as deﬁned in Section 406 of ERISA or Section 4975 of the Code) involving any Plan, (ii) any failure to satisfy the minimum funding",
    # 'extract_7': " (IV) Sale/Leaseback Transactions and Reﬁnancing Indebtedness in respect thereof: $ [ , , ] (V) Reﬁnancing Indebtedness in respect of any such other Indebtedness incurred pursuant to clause 6.01(d)(i) (exclusive of the amount of any Reﬁnancing Indebtedness in respect of (i) the Capital Lease Obligations in respect of the Borrower’s headquarters complex and (ii) Sale/Leaseback Transactions) or 6.01(d)(ii) (Section 6.01(d)(iii)): $ [ , , ] (VI) Pre-existing Indebtedness of acquired Subsidiaries and any Reﬁnancing Indebtedness in respect thereof (Section 6.01(e)): $ [ , , ] (VII) Indebtedness outstanding under Section 6.01(h): $ [ , , ] T otal (II) + (III) + (IV)+(V): $[ , , ] T otal (I)+(II)+(III)+(IV)+(V)+(VI)+)(VII): $[ , , ] 1Cannot exceed $750,000,000. 2Cannot exceed $500,000,000. 3Cannot exceed $3,000,000,000.1 2 3 4 4Cannot exceed $8,000,000,000. Exhbit A to Compliance Certiﬁcate Financial Statements",
    # 'extract_8': "EXHIBIT E [Form of] Conversion/Continuation Notice Reference is made to the Credit Agreement dated as of February 28, 2012 (as amended, restated, supplemented or otherwise modiﬁed from time to time, the “Credit Agreement”), among Facebook, Inc., a Delaware corporation (the “Borrower”), the Lenders party thereto and JPMorgan Chase Bank, N.A., as the Administrative Agent. Capitalized terms used but not otherwise deﬁned herein shall have the meanings speciﬁed in the Credit Agreement. The Borrower hereby requests, in accordance with Section 2.06 of the Credit Agreement, the conversion and/or continuation of Loans, effective as of [mm/dd/yy], as follows: $[ , , ] Eurodollar Rate Loans to be continued with an Interest Period of [ ]'",
    # 'extract_9': "is made to the Credit Agreement dated as of February 28, 2012 (as amended, restated, supplemented or otherwise modiﬁed from time to time, the “Credit Agreement”), among Facebook, Inc., a Delaware corporation (the “Borrower”), the Lenders party thereto and JPMorgan Chase Bank, N.A., as the Administrative Agent. Capitalized terms used but not otherwise deﬁned herein shall have the meanings speciﬁed in the Credit Agreement. Any Permitted Subordinated Indebtedness shall be expressly subordinated to the liquidation, reorganization, insolvency, receivership or a similar proceeding with respect to, or any dissolution or winding-up of, the applicable Credit Party;",
    # 'extract_10': "(b) such Indebtedness shall provide that no direct or indirect payment in respect of such Indebtedness (including payments of interest or principal and the repurchase, redemption, defeasance or other acquisition of such Indebtedness) shall be made (i) during the continuance of any Default or Event of Default in the payment of the principal of or interest on the Obligations and (ii) in the event a Change in Control shall have occurred, until a Notice of Change in Control shall have been delivered by the Borrower and all the outstanding Loans of all Lenders that shall have exercised the right referred to in Section 2.11(b) of the Credit Agreement have been paid in full and the Commitments, if any, of such Lenders have terminated; (c) such Indebtedness shall contain customary standstill provisions for a period of 179 days during the continuance of'}"
}

sample_answer = """
Based on the given credit agreement, the key numerical aspect of limiting indebtedness includes several constraints on what types of debts can be taken on, how much money can be spent on certain activities, and when new subsidiaries can join existing ones. Here's a breakdown of these limits:

[Extract_1]
The Borrower cannot create, incur, assume, or allow to exist any Indebtedness without permission from the lenders.
Indebtedness allowed include those created under the Credit Documents and the Bridge Facility, loans between the Borrower and its own subsidiaries, guaranteed loans made by the Borrower or its subsidiaries, sale/leaseback transactions up to $750 million, refinanced debt up to $750 million, and financing used to acquire fixed assets up to $3 billion per year.
There are also rules about what happens to guarantees made by the Borrower or its subsidiaries, but they don't seem directly tied to numbers themselves.

[Extract_2]
Guaranties made by the Borrower or its subsidiaries must meet certain criteria before being accepted.
For example, no guarantee may cover permissible subordinate debt unless it complies with certain requirements set out elsewhere in the contract. Similarly, no guaranty covering non-permissive indentedness may be valid unless it meets certain standards established by law or industry practice.
Again, while some parts of this section do involve numeric amounts ($750 million), most focus more on qualifications rather than hard limits.

[Extract_3]
This provision sets strict limits on the total amount of debt the Borrower can carry at once, both overall and specifically for different categories of debt.
In general, the maximum level of unsecured debt the Borrower can hold is $3 billion, although there are lower caps for secured debt and special situations like sales/leases back transactions.
These limits apply regardless of whether the debt was acquired through purchase, issuance, or another means.

Overall, then, the main limitation on indebtedness appears to come from Extract_3, which imposes absolute ceilings on various forms of debt based on their type and timing. While the other extracts offer guidelines and preferences regarding acceptable levels of debt, none appear to impose actual numerical limits beyond what's already stated in Extract_3.
"""