extracts = {
    'extract_1': 'Domestic Subsidiary. ARTICLE 6 NEGATIVE COVENANTS Until the Commitments shall have expired or been terminated and the principal of and interest on each Loan and all fees payable hereunder shall have been paid in full, the Borrower covenants and agrees with the Lenders that: Section 6.01. Indebtedness. The Borrower will not, and will not permit any Subsidiary to, create, incur, assume or permit to exist any Indebtedness, except: (a) Indebtedness created under (i) the Credit Documents and (ii) the Bridge Facility; (b) Indebtedness of the Borrower or any Subsidiary owing to the Borrower or any other Subsidiary; provided that (i) such Indebtedness shall not have been transferred to any Person other than the Borrower or any Subsidiary and (ii) any such Indebtedness owing by any Credit Party to a Subsidiary that is not a Credit Party shall be subordinated to the Obligations on terms customary for intercompany subordinated Indebtedness, as reasonably determined by the Administrative Agent; ',
    'extract_2': '(c) Guarantees by the Borrower or any Subsidiary of any Indebtedness of the Borrower or any other Subsidiary, other than (i) Guarantees of Permitted Subordinated Indebtedness if such Guarantees are not permitted by the deﬁnition of the term “Permitted Subordinated Indebtedness” and (ii) Guarantees of Indebtedness referred to in clause (e) below if such Guarantees are not permitted by such clause; (d) (i) Capital Lease Obligations,  (ii) Indebtedness incurred to ﬁnance the acquisition, construction or improvement of any ﬁxed or capital assets or assumed in connection with the acquisition of any such assets, and (iii) Reﬁnancing Indebtedness in respect of any such other Indebtedness incurred pursuant to clause (i) or (ii); provided that (A) the aggregate amount of Sale/Leaseback Transactions and Reﬁnancing Indebtedness in respect thereof shall not exceed $750,000,000 and (B) the aggregate amount of Indebtedness incurred in reliance on this subsection ',
    'extract_3': '(d) shall not exceed $3,000,000,000 at any time outstanding (exclusive of the amount of the Capital Lease Obligations in respect of the Borrower’s headquarters complex and any Reﬁnancing Indebtedness in respect thereof) and (C) in the case of any Indebtedness referred to in clause (ii) above, such Indebtedness is incurred prior to or within 270 days after such acquisition or the completion of such construction or improvement and the principal amount of such Indebtedness does not exceed the cost of acquiring, constructing or improving such ﬁxed or capital assets; 53 (e) Indebtedness of any Person that becomes a Subsidiary (or of any Person not previously a Subsidiary that is merged or consolidated with or into a Subsidiary in a transaction permitted hereunder) after the date hereof, and Reﬁnancing Indebtedness in respect thereof; ',
    'extract_4': 'provided that (i) such Indebtedness exists at the time such Person becomes a Subsidiary (or is so merged or consolidated) and is not created in contemplation of or in connection with such Person becoming a Subsidiary (or such merger or consolidation) and (ii) the aggregate principal amount of Indebtedness permitted by this clause (e) shall not exceed $500,000,000 at any time outstanding; (f) Indebtedness owed in respect of overdrafts and related liabilities arising from treasury, depository and cash management services or in connection with any automated clearing-house transfers of funds; (g) Permitted Subordinated Indebtedness; and (h) other Indebtedness of the Borrower or any Subsidiary; provided that the aggregate principal amount of such Indebtedness,',
}

new_extracts = {
    'extract_1': "RAG is designed to address the limitations of traditional language models that generate responses based solely on the input they receive and the information they have been trained on. While these models are effective in many scenarios, they can struggle with tasks that require specific, factual knowledge or the ability to reference multiple sources of information.",
    'extract_2': "The Borrower and its subsidiaries cannot take on new debt unless it's specifically allowed by the credit agreement, was owed within the company, or is a Guarantee for another subsidiary's allowed debt.",
    'extract_3': "The Borrower can take on debt for capital leases/asset purchases (up to $3 billion).  There's an additional $750 million limit for sale/leasebacks. Debt is allowed for newly acquired subsidiaries, up to $500 million.",
    'extract_4': "The purest type of electronic clinical data which is obtained at the point of care at a medical facility, hospital, clinic or practice. Often referred to as the electronic medical record (EMR), the EMR is generally not available to outside researchers. The data collected includes administrative and demographic information, diagnosis, treatment, prescription drugs, laboratory tests, physiologic monitoring data, hospitalization, patient insurance, etc.",
    'extract_5': "The Borrower and its subsidiaries can take on debt for overdrafts, subordinated debt, and other purposes, but there is an overall limit (amount to be determined).",
    'extract_7': "Until the loan is repaid, the Borrower agrees to restrictions on taking on new debt (Indebtedness), as outlined in Section 6.01 of the agreement.",
}
